name: PSR12 CodingStandard

on:
  push: 
    branches: [ master ] 
  pull_request:
    branches: [ master ]

jobs:

  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP Code Sniffer
        run: |
          composer require --dev squizlabs/php_codesniffer
       
      - name: Check coding standards
        run: ./vendor/bin/phpcs --standard="phpcs.xml" --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1 -v ./app ./tests

      - name: Fixing Linitng
        run: ./vendor/bin/phpcbf -q --standard=phpcs.xml ./app ./tests > /dev/null || true

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply phpcbf formatting changes